const cancionesExtras = [
  { titulo: "", archivo: "catriel_tetas.mp3" },
  { titulo: "", archivo: "tameimpala_letithappen.mp3" },
  { titulo: "", archivo: "Grimes_Genesis.mp3" },
  { titulo: "", archivo: "duranduran_comeundone.mp3" },
  { titulo: "", archivo: "duki_goteo.mp3" },
  { titulo: "Anuncio 1", archivo: "Ra1.mp3", artista: "Publicidad Radio" },
  { titulo: "", archivo: "kaseo_yemen.mp3" },
  { titulo: "", archivo: "lazarus_ambient.mp3" },
  { titulo: "", archivo: "justice_dance.mp3" },
  { titulo: "Anuncio 2", archivo: "Ra2.mp3", artista: "Publicidad Radio" },
  { titulo: "", archivo: "postmalone_tema.mp3" },
  { titulo: "", archivo: "tameimpala_lessiknow.mp3" },
  { titulo: "Anuncio 3", archivo: "Ra3.mp3", artista: "Publicidad Radio" },
  { titulo: "", archivo: "brianeno_therewerebells.mp3" },
  { titulo: "", archivo: "alasdecristal.mp3" },
  { titulo: "Anuncio 4", archivo: "Ra4.mp3", artista: "Publicidad Radio" },
  { titulo: "", archivo: "entredostierras.mp3" },
  { titulo: "", archivo: "LosingMyreligion.MP3" },
  { titulo: "", archivo: "EyeInTheSky.mp3" },
  { titulo: "", archivo: "EsEpico.MP3" },
  { titulo: "", archivo: "lady.mp3" },
  { titulo: "", archivo: "Comoelagua.MP3" },
  { titulo: "Anuncio 5", archivo: "Ra5.mp3", artista: "Publicidad Radio" },
  { titulo: "", archivo: "Lapluie.mp3" },
  { titulo: "", archivo: "BillieJean.MP3" },
  { titulo: "Anuncio 6", archivo: "Ra6.mp3", artista: "Publicidad Radio" },
  { titulo: "", archivo: "PutOnYourRedShoes.MP3" },
  { titulo: "", archivo: "WithYou.mp3" },
  { titulo: "", archivo: "PiensoenTuMira.MP3" },
  { titulo: "", archivo: "SoldaditoMarinero.mp3" },
  { titulo: "Anuncio 7", archivo: "Ra7.mp3", artista: "Publicidad Radio" },
  { titulo: "", archivo: "UnderPressure.MP3" },
  { titulo: "Anuncio 8", archivo: "Ra8.mp3", artista: "Publicidad Radio" },
  { titulo: "", archivo: "ElSitioDeMiRecreo.mp3" },
  { titulo: "", archivo: "VivirParaContarlo.MP3" },
  { titulo: "", archivo: "Cheese.mp3" },
  { titulo: "", archivo: "RhythmTakesControl.MP3" },
  { titulo: "", archivo: "EnjoyTheSilence.mp3" },
  { titulo: "Anuncio 9", archivo: "Ra9.mp3", artista: "Publicidad Radio" },
  { titulo: "", archivo: "EstandoContigo.MP3" },
  { titulo: "", archivo: "DuendeGarrapata.mp3" },
  { titulo: "", archivo: "NeverAgain.mp3" },
  { titulo: "", archivo: "RainbowInTheSky.mp3" },
  { titulo: "", archivo: "Alba.MP3" },
  { titulo: "", archivo: "DiasDeVerano.mp3" },
  { titulo: "Anuncio 10", archivo: "Ra10.mp3", artista: "Publicidad Radio" },
  { titulo: "", archivo: "TodoSeTransforma.MP3" },
  { titulo: "", archivo: "TamboresDeGuerra.mp3" },
  { titulo: "", archivo: "Crawling.mp3" },
  { titulo: "", archivo: "Pop.MP3" },
  { titulo: "", archivo: "RosaMaria.mp3" },
  { titulo: "", archivo: "YouthOfTheNation.MP3" },
  { titulo: "Anuncio 11", archivo: "Ra11.mp3", artista: "Publicidad Radio" },
  { titulo: "", archivo: "MalditoDuende.mp3" },
  { titulo: "", archivo: "OnAndOn.MP3" },
  { titulo: "", archivo: "Rollin.mp3" },
  { titulo: "Anuncio 12", archivo: "Ra12.mp3", artista: "Publicidad Radio" },
  { titulo: "", archivo: "Perdidoenlaciudad.MP3" },
  { titulo: "", archivo: "Sucede.mp3" },
  { titulo: "", archivo: "TwoEnemigos.MP3" },
  { titulo: "", archivo: "Puta.mp3" },
  { titulo: "", archivo: "TusLabiosPaMi.mp3" },
  { titulo: "Anuncio 13", archivo: "Ra13.mp3", artista: "Publicidad Radio" },
  { titulo: "", archivo: "Tengo.mp3" },
  { titulo: "", archivo: "Andaluzdenacimiento.MP3" },
  { titulo: "", archivo: "livinalie.mp3" },
  { titulo: "", archivo: "BeautifulWorld.MP3" },
  { titulo: "", archivo: "Medieval.mp3" },
  { titulo: "", archivo: "Crawling.mp3" }
];